### ISSUE TITLE
[1.17.1] server still crash with new version v1.97.3-hotfix

### ISSUE THREAD

**Issue by MSandro** [cc-tweaked/cc-restitched#39] opened 2021-12-18 22:07 UTC
## Useful information to include:
 - Minecraft version 1.17.1
 - CC: Restitched version 1.97.3-hotfix
 - Detailed reproduction steps: just start the server with Fabric Loader 0.12.12 and Fabric API 0.44.0
 -  Logs: 
```
[21:46:45] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2588.method_11025(class_2588.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.class_2588.method_27659(class_2588.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_2561.method_27657(class_2561.java:96) ~[server-intermediary.jar:?]
	at net.minecraft.class_5348.getString(class_5348.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_2561.getString(class_2561.java:39) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.exceptions.CommandSyntaxException.<init>(CommandSyntaxException.java:27) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.exceptions.SimpleCommandExceptionType.createWithContext(SimpleCommandExceptionType.java:21) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.StringReader.readDouble(StringReader.java:142) ~[server-intermediary.jar:?]
	at net.minecraft.class_2278.method_9743(class_2278.java:41) ~[server-intermediary.jar:?]
	at net.minecraft.class_2280.method_9750(class_2280.java:87) ~[server-intermediary.jar:?]
	at net.minecraft.class_2277.method_9738(class_2277.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_2277.parse(class_2277.java:21) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.tree.ArgumentCommandNode.isValidInput(ArgumentCommandNode.java:91) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:102) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:113) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:113) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.CommandDispatcher.findAmbiguities(CommandDispatcher.java:695) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:235) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:88) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:147) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 7 more
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: block.minecraft.nether_wart_block=Crimson Wart Block and block.minecraft.nether_wart_block=Nether Wart Block
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186) ~[server-intermediary.jar:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102) ~[server-intermediary.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88) ~[server-intermediary.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359) ~[server-intermediary.jar:?]
	at net.minecraft.class_2477.method_29429(class_2477.java:45) ~[server-intermediary.jar:?]
	at net.minecraft.class_2477.<clinit>(class_2477.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_2588.method_11025(class_2588.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.class_2588.method_27659(class_2588.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_2561.method_27657(class_2561.java:96) ~[server-intermediary.jar:?]
	at net.minecraft.class_5348.getString(class_5348.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_2561.getString(class_2561.java:39) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.exceptions.CommandSyntaxException.<init>(CommandSyntaxException.java:27) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.exceptions.SimpleCommandExceptionType.createWithContext(SimpleCommandExceptionType.java:21) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.StringReader.readDouble(StringReader.java:142) ~[server-intermediary.jar:?]
	at net.minecraft.class_2278.method_9743(class_2278.java:41) ~[server-intermediary.jar:?]
	at net.minecraft.class_2280.method_9750(class_2280.java:87) ~[server-intermediary.jar:?]
	at net.minecraft.class_2277.method_9738(class_2277.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_2277.parse(class_2277.java:21) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.tree.ArgumentCommandNode.isValidInput(ArgumentCommandNode.java:91) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:102) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:113) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.tree.CommandNode.findAmbiguities(CommandNode.java:113) ~[server-intermediary.jar:?]
	at com.mojang.brigadier.CommandDispatcher.findAmbiguities(CommandDispatcher.java:695) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:235) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:88) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:147) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 7 more
```

**Comment by Merith-TK** [comment] 2021-12-18 22:24
Send the full logs please.

https://modrinth.com/mod/notenoughcrashes
https://modrinth.com/mod/badstdout

add these as well

because that error is not an issue caused by CC:R *alone*, there is another mod present on your server that overwrites translation keys.

My guess is Adorn, Blockus, or simular mods

**Comment by toad-dev** [comment] 2021-12-18 22:27
I think there's been a miscommunication. The latest commit in the 1.17 branch was just to fix some mod metadata stuff. It didn't include the fix for this translation key bug that was released in 1.99.2-alpha1. This seems like an important thing to fix though, so I will port that commit over to 1.17 at some point. No ETA as 1.17 is not a priority of mine at the moment.

**Comment by MSandro** [comment] 2021-12-18 23:47
cc-restiched-1.97.2.jar worked fine, not sure why cc-restiched-1.97.3 crashes my server.
thanks, I've added the mods. But it does not produce a crash report, but here is the latest.log: https://mclo.gs/KNf2Kle

**Comment by Merith-TK** [comment] 2021-12-19 06:03
please upload the file of the logs, not just the snibbit
use https://mclo.gs to upload, it will auto censor sensitive info such as IP's and the like. 

i request the full log, not just a snibbit

**Comment by MSandro** [comment] 2021-12-20 06:19
https://mclo.gs/KNf2Kle

**Comment by Merith-TK** [comment] 2021-12-20 06:32
did.... did your logs trunicate? as in strip themselves?? I had that issue for a while and couldnt figure out why...

anyways
https://github.com/cc-tweaked/cc-restitched/actions/runs/1599586392

upload the `cc-restitched-<versionumber>.jar` from the artifacts zip to the server and try again, this *should* fix the issue

**Comment by Merith-TK** [comment] 2021-12-21 00:04
assuming this is fixed in this build?

**Comment by MSandro** [comment] 2021-12-21 12:07
yes it works, thanks

**Closed as completed** 2021-12-21 12:13 UTC
Labels: bug

**Comment by MSandro** [comment] 2021-12-21 12:31
``
